# Generated by Django 5.2.3 on 2025-08-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=45)),
                ('piso', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
