# Generated by Django 5.2.3 on 2025-07-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='esatado',
            field=models.BooleanField(default=False),
        ),
    ]
