# Generated by Django 5.2.3 on 2025-07-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_esatado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='esatado',
            new_name='libre',
        ),
    ]
